### ISSUE TITLE
部署完了页面显示{"message":"Not Found"}

### ISSUE THREAD

**Issue by LiteraturePro** [jneeee/taskbox#3]
你好，部署完成后，页面显示{"message":"Not Found"}，

URL：https://blwwid8b9f.execute-api.ap-southeast-1.amazonaws.com/

请问一下是什么原因造成的呀

**Comment by jneeee** [comment]
Hi 
方便贴一下后台的 cloudwatch日志吗
![image](https://github.com/jneeee/taskbox/assets/27620242/b838a10d-47e3-4405-b27e-7a62c54b0a52)

**Comment by LiteraturePro** [comment]
我好像都没有这个日志组，哎
![image](https://github.com/jneeee/taskbox/assets/65801567/d7a9e1b1-4467-4aeb-a8ec-2479c94e410e)
![image](https://github.com/jneeee/taskbox/assets/65801567/40f28dc3-d3d2-429e-9879-acc693f27b69)

**Comment by jneeee** [comment]
没有日志不太好搞呀，你可以试试函数配置界面的 函数 URL 是不是一样的结果，再检查一下 IAM 角色是不是这些权限
![image](https://github.com/jneeee/taskbox/assets/27620242/df67c751-685f-4623-8517-071e69831e6a)
![image](https://github.com/jneeee/taskbox/assets/27620242/2ded47d3-5089-4c83-9cef-7dc28939431e)
